### ISSUE TITLE
Copied

### ISSUE THREAD

**Issue by aayushgenius** [NightZan999/Your-Coding-Journey#2]
I have no idea why but every part of code in https://github.com/NightZan999/Your-Coding-Journey/tree/master/Games/Speed%20Test%20Game is copied from https://github.com/sayantanm19/js-simple-typing-game/ I have issued a request there too, so please bring it down

**Comment by superzackx** [comment]
> I have no idea why but every part of code in https://github.com/NightZan999/Your-Coding-Journey/tree/master/Games/Speed%20Test%20Game is copied from https://github.com/sayantanm19/js-simple-typing-game/ I have issued a request there too, so please bring it down

Dude, I am not the owner. Tell @NightZan999.

**Comment by NightZan999** [comment]
Well, technically @aayushgenius we got it from a website. We will shortly remove it

**Comment by NightZan999** [comment]
I deleted the code and updated our policies and more!
